// Central UI string table. One entry per user-visible string.
// Read through Scene.prototype.t(key) / window.t(key) — never index this directly.
// 'bis' values are intentionally empty; t() falls back to 'en' until they are filled.
// streetView arrow labels are deliberately NOT here, and must never be added:
// they are control-flow identifiers, not display text. Nothing renders them to
// the player (those arrows are flat untextured discs) — the string itself is the
// discriminator, read via .includes('Back') and === comparisons to pick arrow
// material colour and drive forward/back selection. Translating them would break
// navigation for zero visible benefit. See the warning above this.positions in
// scenes/streetView.js.

window.Strings = {
    'cafe.yfc-board.label': { en: 'YFC Board', bis: 'YFC Board' },
    'cafe.yfc-board.description': { en: 'Aside from the owners\' passion in bringing the farm to the cup, they bring the same passion in dedicating their time in building a Christ-centered community. For over ten years, they faithfully serve as Chapter 5 coordinators of the Youth for Christ Pangantucan Chapter, dedicating their time in being committed to touching countless lives through consistent providing leadership, service, guidance and support to the municipalities of Kalilangan, Pangantucan, and Wao. Their continued dedication reflects a life of selfless service, inspiring communities to grow in faith, unity, and love for God.', bis: 'Gawas sa ilang kadasig sa pagdala sa kape gikan sa umahan ngadto sa tasa, susama usab ang ilang kadasig sa paggahin og panahon alang sa pagtukod og komunidad nga nagsentro kang Kristo. Sulod sa kapin napulo ka tuig, matinud-anon silang nag-alagad isip Chapter 5 coordinators sa Youth for Christ Pangantucan Chapter, nga naghatag og pagpangulo, pag-alagad, giya, ug suporta sa mga lungsod sa Kalilangan, Pangantucan, ug Wao. Ang ilang padayon nga dedikasyon nagpakita og kinabuhi sa walay hakog nga pag-alagad, nga nag-awhag sa mga komunidad nga motubo sa pagtuo, panaghiusa, ug gugma sa Dios.' },
    'cafe.finca-logo.label': { en: 'Finca de Garces Logo', bis: 'Logo sa Finca de Garces' },
    'cafe.finca-logo.description': { en: 'This was Finca de Garces\' old logo. Owners decided to renew their branding years later to bring a new face to Finca de Garces while preserving the farm\'s roots.', bis: 'Kini ang daan nga logo sa Finca de Garces. Gibag-o sa mga tag-iya ang ilang branding paglabay sa mga tuig aron mahatagan og bag-ong dagway ang Finca de Garces, apan gitipigan gihapon ang gamot sa umahan.' },
    'cafe.bar.label': { en: 'The Bar', bis: 'Ang Bar' },
    'cafe.bar.description': { en: 'The bar is where specialty coffee is meticulously crafted, served and discussed. Unlike traditional and commercial cafes, this is where the owners showcase the careful process of pouring a cup of specialty coffee while they engage with visitors.', bis: 'Ang bar mao ang dapit diin maampingong ginahimo, gisilbi, ug gihisgotan ang specialty coffee. Lahi sa naandan ug komersyal nga mga café, dinhi gipakita sa mga tag-iya ang maampingong proseso sa pagbubo sa usa ka tasa sa specialty coffee samtang nakigsulti sa mga bisita.' },
    'cafe.coffee-brewing.label': { en: 'Brew Coffee', bis: 'Paghimo og Kape' },
    'cafe.coffee-brewing.description': { en: '', bis: '' },
    'cafe.chill-section.label': { en: 'Chill Section', bis: 'Chill Section' },
    'cafe.chill-section.description': { en: 'The owners always emphasize creating connections. The chill section is where customers can play with games, cards and indulge in books to create conversation and a relaxing atmosphere whilst enjoying a cup of coffee.', bis: 'Kanunay gipasiugda sa mga tag-iya ang paghimo og koneksyon. Ang chill section mao ang dapit diin ang mga bisita makadula og mga dula ug baraha, ug makabasa og mga libro aron makamugna og panag-istoryahanay ug hayahay nga palibot samtang nagtagamtam sa usa ka tasa sa kape.' },
    'cafe.exit-to-exterior.label': { en: 'To Nursery', bis: 'Padulong sa Binhianan' },
    'cafe.exit-to-exterior.label.complete': { en: 'Go Outside', bis: 'Gawas sa Café' },
    'cafe.exit-to-exterior.description': { en: 'Click to step outside the cafe.', bis: 'I-klik aron mogawas sa café.' },
    'cafe.quiz.question': { en: 'What was the original purpose of opening Alegre Café & Roastery?', bis: 'Unsa ang orihinal nga katuyoan sa pag-abli sa Alegre Café & Roastery?' },
    'cafe.quiz.choice.0': { en: 'To become the largest coffee exporter in the region.', bis: 'Aron mahimong pinakadako nga tig-eksport og kape sa rehiyon.' },
    'cafe.quiz.choice.1': { en: 'To create a place where people could gather, share stories, and enjoy coffee grown on the family\'s farm.', bis: 'Aron makahimo og lugar diin ang mga tawo makatapok, mag-ambitay og mga istorya, ug motagamtam sa kapeng gipatubo sa ilang kaugalingong umahan.' },
    'cafe.quiz.choice.2': { en: 'To sell imported specialty coffee.', bis: 'Aron makabaligya og imported nga specialty coffee.' },
    'cafe.quiz.choice.3': { en: 'To promote tourism in Pangantucan.', bis: 'Aron mapalambo ang turismo sa Pangantucan.' },
    'cafe.quiz.clue': { en: 'Think about why the family opened the café — it wasn\'t about scale or selling someone else\'s beans.', bis: 'Hunahunaa kung ngano nga giablihan sa pamilya ang café — dili kini mahitungod sa gidak-on o sa pagbaligya sa liso sa uban.' },
    'cafe.quiz.feedback': { en: 'Correct! Alegre Café & Roastery was created as a place where people can connect through coffee while learning the story behind every cup.', bis: 'Sakto! Ang Alegre Café & Roastery gimugna isip lugar diin ang mga tawo magkaduol pinaagi sa kape samtang nakat-on sa istorya sa likod sa matag tasa.' },
    'cafeExterior.enter-interior.label': { en: 'Enter Cafe', bis: 'Sulod sa Café' },
    'cafeExterior.enter-interior.description': { en: 'Click to go inside.', bis: 'I-klik aron mosulod.' },
    'cafeExterior.to-roastery.label': { en: 'Enter the Roastery', bis: 'Sulod sa Sanlaganan' },
    'cafeExterior.to-roastery.description': { en: 'Step inside and see where the coffee is roasted.', bis: 'Sulod ug tan-awa kung diin gisanlag ang kape.' },
    'cafeExterior.to-nursery.label': { en: 'Enter the Nursery', bis: 'Sulod sa Binhianan' },
    'cafeExterior.to-nursery.description': { en: 'Visit the coffee seedling nursery.', bis: 'Duawa ang binhianan sa mga tanom nga kape.' },
    'cafeExterior.walk-to-farm.label': { en: 'Walk to the Farm', bis: 'Baktas Padulong sa Umahan' },
    'cafeExterior.walk-to-farm.description': { en: 'Take the path from the cafe to the coffee farm.', bis: 'Agiha ang dalan gikan sa café padulong sa umahan sa kape.' },
    'nursery.back-to-exterior.label': { en: 'Walk to the Farm', bis: 'Baktas Padulong sa Umahan' },
    'nursery.back-to-exterior.description': { en: 'Take the path to the coffee farm.', bis: 'Agiha ang dalan padulong sa umahan sa kape.' },
    'nursery.seedlings.label': { en: 'Seedlings', bis: 'Mga Punla' },
    'nursery.seedlings.description': { en: 'This is where the coffee journey begins. Young plants are nurtured under careful shade and watering conditions before being transplanted to the farm.', bis: 'Dinhi magsugod ang panaw sa kape. Ang batan-ong mga tanom giatiman ubos sa hustong landong ug pagbisbis sa dili pa kini ibalhin ngadto sa umahan.' },
    'nursery.net-shading.label': { en: 'Net Shading', bis: 'Net Shading' },
    'nursery.net-shading.description': { en: 'Black net shading protects the seedlings from direct sun and helps regulate temperature.', bis: 'Ang itom nga net shading nagpanalipod sa mga punla gikan sa direktang init sa adlaw ug nagtabang sa pagkontrol sa temperatura.' },
    'nursery.quiz.question': { en: 'How long do young coffee seedlings usually stay in polybags before they are ready for planting?', bis: 'Unsa kadugay magpabilin ang batan-ong mga punla sa kape sa polybags sa dili pa kini andam itanom?' },
    'nursery.quiz.choice.0': { en: '1–2 months', bis: '1–2 ka bulan' },
    'nursery.quiz.choice.1': { en: '3–4 months', bis: '3–4 ka bulan' },
    'nursery.quiz.choice.2': { en: '6–12 months', bis: '6–12 ka bulan' },
    'nursery.quiz.choice.3': { en: '2 years', bis: '2 ka tuig' },
    'nursery.quiz.clue': { en: 'Longer than a few months — roots need real time to establish before transplanting.', bis: 'Mas dugay pa kaysa pipila ka bulan — ang gamot nagkinahanglan og tinuod nga panahon aron molig-on sa dili pa ibalhin.' },
    'nursery.quiz.feedback': { en: 'Correct! Seedlings remain in polybags for about six to twelve months, allowing them to develop strong roots before being transplanted.', bis: 'Sakto! Ang mga punla magpabilin sa polybags sulod sa unom ngadto sa dose ka bulan, aron molig-on ang ilang gamot sa dili pa kini ibalhin.' },
    'roastery.back-to-exterior.label': { en: 'Exit to Cafe', bis: 'Balik sa Café' },
    'roastery.back-to-exterior.description': { en: 'Return to the cafe garden.', bis: 'Balik sa hardin sa café.' },
    'roastery.roasting-machine.label': { en: 'Roasting Machine', bis: 'Makina sa Pagsanlag' },
    'roastery.roasting-machine.description': { en: 'The roaster applies controlled heat to green coffee beans, moving them through drying, first crack, and development — the stages that build the sugars, acids, and oils responsible for flavour and aroma. Roast time and temperature are adjusted to draw out each bean\'s best character before cooling and packaging.', bis: 'Ang roaster naghatag og kontrolado nga kainit sa lunhaw nga liso sa kape, nga giagi kini sa pagpauga, first crack, ug development — ang mga hugna nga naghimo sa mga asukar, asido, ug lana nga maoy hinungdan sa lami ug kahumot. Ang gidugayon ug temperatura sa pagsanlag gi-adjust aron mogawas ang labing maayong kinaiya sa matag liso sa dili pa kini pabugnawon ug iputos.' },
    'roastery.roasting-beans-transition.label': { en: 'Roasting Beans', bis: 'Pagsanlag sa Liso' },
    'roastery.roasting-beans-transition.description': { en: 'Watch the beans roast', bis: 'Tan-awa ang pagsanlag sa mga liso' },
    'roastery.green-bean-packs.label': { en: 'Green Bean Packs', bis: 'Mga Pakete sa Lunhaw nga Liso' },
    'roastery.green-bean-packs.description': { en: 'Arabica grows at higher elevations and is known for a smoother, more complex, slightly sweet profile with milder acidity. Robusta is hardier, carries more caffeine, and brings a bolder, more bitter character — often used to add body and crema.', bis: 'Ang Arabica motubo sa mas hataas nga dapit ug nailhan sa mas hamis, mas komplikado, ug gamay nga tam-is nga lami uban sa mas hinay nga aslom. Ang Robusta mas kusgan, mas daghan og caffeine, ug naghatag og mas isog ug mas pait nga kinaiya — kasagarang gigamit aron madugangan ang katambok ug crema.' },
    'roastery.quiz.question': { en: 'What does the \'first crack\' during roasting indicate?', bis: 'Unsa ang gipasabot sa \'first crack\' panahon sa pagsanlag?' },
    'roastery.quiz.choice.0': { en: 'The beans are ready to be planted.', bis: 'Andam na ang mga liso nga itanom.' },
    'roastery.quiz.choice.1': { en: 'The beans begin developing their full coffee flavor.', bis: 'Nagsugod na ang paglambo sa hingpit nga lami sa kape.' },
    'roastery.quiz.choice.2': { en: 'The beans have finished cooling.', bis: 'Human na og bugnaw ang mga liso.' },
    'roastery.quiz.choice.3': { en: 'The beans are ready to be brewed immediately.', bis: 'Andam na ang mga liso nga himoong kape dayon.' },
    'roastery.quiz.clue': { en: 'First crack happens in the middle of roasting, not at the end — it\'s about flavor developing.', bis: 'Ang first crack mahitabo sa tunga sa pagsanlag, dili sa katapusan — mahitungod kini sa paglambo sa lami.' },
    'roastery.quiz.feedback': { en: 'Correct! The first crack signals an important stage where the beans expand and develop the flavors and aromas we associate with coffee.', bis: 'Sakto! Ang first crack timailhan sa importanteng hugna diin molapad ang mga liso ug molambo ang lami ug kahumot nga atong nailhan sa kape.' },
    'streetView.quiz.question': { en: 'Why is organic fertilizer added before planting a coffee seedling?', bis: 'Ngano nga gibutangan og organikong abono sa dili pa itanom ang punla sa kape?' },
    'streetView.quiz.choice.0': { en: 'To make the soil richer and help the roots grow well.', bis: 'Aron mahimong mas tambok ang yuta ug motubo og maayo ang gamot.' },
    'streetView.quiz.choice.1': { en: 'To make harvesting easier.', bis: 'Aron mas sayon ang pag-ani.' },
    'streetView.quiz.choice.2': { en: 'To speed up roasting.', bis: 'Aron mapaspasan ang pagsanlag.' },
    'streetView.quiz.choice.3': { en: 'To change the flavor of the coffee immediately.', bis: 'Aron mausab dayon ang lami sa kape.' },
    'streetView.quiz.clue': { en: 'Think about what the fertilizer touches first — it goes into the hole, before the tree ever grows.', bis: 'Hunahunaa kung unsa ang unang mahikapan sa abono — mosulod kini sa lungag, sa dili pa motubo ang punoan.' },
    'streetView.quiz.feedback': { en: 'Correct! Healthy coffee trees begin with healthy soil. Preparing the planting hole with organic fertilizer gives young trees the best possible start.', bis: 'Sakto! Ang himsog nga punoan sa kape magsugod sa himsog nga yuta. Ang pag-andam sa lungag pinaagi sa organikong abono naghatag sa batan-ong punoan sa labing maayong sinugdanan.' },
    'quiz.harvesting.question': { en: 'Which coffee cherries are selected during harvesting?', bis: 'Unsang mga bunga sa kape ang pilion panahon sa pag-ani?' },
    'quiz.harvesting.choice.0': { en: 'Green cherries', bis: 'Berde nga mga bunga' },
    'quiz.harvesting.choice.1': { en: 'Yellow cherries', bis: 'Dalag nga mga bunga' },
    'quiz.harvesting.choice.2': { en: 'Bright red, fully ripe cherries', bis: 'Hayag og pula, hinog kaayo nga mga bunga' },
    'quiz.harvesting.choice.3': { en: 'All cherries on the branch', bis: 'Tanang bunga sa sanga' },
    'quiz.harvesting.clue': { en: 'Look closely at the colour of the cherries the pickers reach for.', bis: 'Tan-awa pag-ayo ang kolor sa mga bunga nga gikuha sa mga mamumupo.' },
    'quiz.harvesting.feedback': { en: 'Correct! Only fully ripe cherries are hand-picked to ensure the highest coffee quality.', bis: 'Sakto! Ang hinog na kaayo nga mga bunga lamang ang gipupo pinaagi sa kamot aron masiguro ang labing taas nga kalidad sa kape.' },
    'quiz.backToTheCafe.question': { en: 'What is the main message behind every cup served at Alegre Café & Roastery?', bis: 'Unsa ang pangunang mensahe sa likod sa matag tasa nga gisilbi sa Alegre Café & Roastery?' },
    'quiz.backToTheCafe.choice.0': { en: 'Coffee is simply a beverage.', bis: 'Ang kape usa lamang ka ilimnon.' },
    'quiz.backToTheCafe.choice.1': { en: 'Every cup reflects the care, values, and dedication of the Garces family and their community.', bis: 'Ang matag tasa nagpakita sa pag-atiman, mga bili, ug dedikasyon sa pamilyang Garces ug sa ilang komunidad.' },
    'quiz.backToTheCafe.choice.2': { en: 'Coffee is only about roasting.', bis: 'Ang kape mahitungod ra sa pagsanlag.' },
    'quiz.backToTheCafe.choice.3': { en: 'Great coffee depends only on expensive equipment.', bis: 'Ang maayong kape nagdepende ra sa mahal nga kagamitan.' },
    'quiz.backToTheCafe.clue': { en: 'The answer is about people and values, not equipment or a single step in the process.', bis: 'Ang tubag mahitungod sa mga tawo ug mga bili, dili sa kagamitan o sa usa lamang ka hugna sa proseso.' },
    'quiz.backToTheCafe.feedback': { en: 'Correct! Every cup represents the journey from seed to cup, honoring the people, the land, and the passion that made it possible.', bis: 'Sakto! Ang matag tasa nagrepresentar sa panaw gikan sa liso ngadto sa tasa, nga nagpasidungog sa mga tawo, sa yuta, ug sa gugma nga naghimo niini nga posible.' },
    'quiz.finalChallenge.question': { en: 'Complete the sentence: \'Every cup of coffee begins with...\'', bis: 'Kompletoha ang mga pulong: \'Ang matag tasa sa kape magsugod sa...\'' },
    'quiz.finalChallenge.choice.0': { en: 'A coffee shop', bis: 'Usa ka coffee shop' },
    'quiz.finalChallenge.choice.1': { en: 'A roasting machine', bis: 'Usa ka makina sa pagsanlag' },
    'quiz.finalChallenge.choice.2': { en: 'A strong foundation, patient care, and dedicated people.', bis: 'Lig-ong pundasyon, mapailubong pag-atiman, ug mga tawong dedikado.' },
    'quiz.finalChallenge.choice.3': { en: 'A coffee grinder', bis: 'Usa ka galingan sa kape' },
    'quiz.finalChallenge.clue': { en: 'Think back to where the journey actually started — before any machine was involved.', bis: 'Hinumdomi kung asa gyud nagsugod ang panaw — sa wala pa moapil ang bisan unsang makina.' },
    'quiz.finalChallenge.feedback': { en: 'Congratulations! You\'ve completed the Coffee Journey. Thank you for exploring the story of Alegre Café & Roastery and discovering how every cup is shaped by the land, the people, and generations of dedication. We hope you\'ll carry this story with you every time you enjoy a cup of coffee. ☕', bis: 'Congratulations! Nahuman na nimo ang Panaw sa Kape. Salamat sa pagsuhid sa istorya sa Alegre Café & Roastery ug sa pagkat-on kung giunsa paghulma sa yuta, sa mga tawo, ug sa mga henerasyon sa dedikasyon ang matag tasa. Hinaot nga dad-on ninyo kini nga istorya sa matag higayon nga motagamtam kamo og kape. ☕' },
    'ui.nursery.toFarm': { en: 'To Farm', bis: 'Padulong sa Umahan' },
    'ui.video.continue': { en: 'Continue', bis: 'Padayon' },
    'ui.video.roasteryPrompt': { en: 'Select Continue to visit the roastery', bis: 'I-klik ang Padayon aron moadto sa sanlaganan' },
    'ui.quiz.correct': { en: 'Correct!', bis: 'Sakto!' },
    'ui.clue.ahead': { en: 'It\'s right in front of you', bis: 'Naa ra sa imong atubangan' },
    'ui.clue.right': { en: 'Look to your right', bis: 'Tan-aw sa imong tuo' },
    'ui.clue.left': { en: 'Look to your left', bis: 'Tan-aw sa imong wala' },
    'ui.clue.behind': { en: 'Turn around — it\'s behind you', bis: 'Lingi — naa sa imong likod' },

    // Farm close-up hunt hints. Shown while the golden disc at farm1-4 is unfound;
    // keyed by the player's current position. Display text, unrelated to arrow labels.
    'ui.farm.hint.farm1-1': { en: 'Keep heading forward.', bis: 'Padayon lang sa pag-adto sa unahan.' },
    'ui.farm.hint.farm1-2': { en: 'Explore the area ahead.', bis: 'Suroya ang dapit sa unahan.' },
    'ui.farm.hint.farm1-3': { en: 'So close. Moving forward should help.', bis: 'Duol na kaayo. Padayon lang sa unahan.' },
    'ui.farm.hint.farm1-4': { en: 'You\'re really close — try looking down.', bis: 'Duol na kaayo ka — sulayi og tan-aw sa ubos.' },
    'ui.farm.hint.farm1-5': { en: 'You\'ve gone a bit far. Move back a little.', bis: 'Nalapas na ka og gamay. Balik og diyutay.' },
    'ui.farm.hint.default': { en: 'Look around for the golden button.', bis: 'Pangitaa ang bulawanon nga button sa imong palibot.' },

    // Gate-marker buttons (keyed by gate.ref in voData.js)
    'ui.gate.default': { en: 'Watch', bis: 'Tan-awa' },
    'ui.gate.mapZoom': { en: 'Continue', bis: 'Padayon' },
    'ui.gate.aerial': { en: 'Continue', bis: 'Padayon' },
    'ui.gate.farmerMontage': { en: 'Continue', bis: 'Padayon' },
    'ui.gate.ownerInterview': { en: 'Hear the story behind Granja Alegre', bis: 'Paminawa ang istorya sa luyo sa Granja Alegre' },
    'ui.gate.treePhoto': { en: 'See the trees', bis: 'Tan-awa ang mga punoan' },
    'ui.gate.roasterVideo': { en: 'Watch the roaster', bis: 'Tan-awa ang makina sa pagsanlag' },
    'ui.gate.brewingPOV': { en: 'See the brewing', bis: 'Tan-awa ang paghimo og kape' },
    'ui.gate.polybag': { en: 'Get a closer look at the seedlings', bis: 'Tan-awa pag-ayo ang mga punla' },
    'ui.gate.monitoring': { en: 'Learn about monitoring', bis: 'Hibaloi ang bahin sa pagbantay' },

    // Mini-quiz UI. NOTE: the correct answer is matched by string equality against
    // the option text, so a translated option must be paired with the same key.
    'ui.miniquiz.wrongPrefix': { en: 'Wrong.', bis: 'Sayop.' },
    'ui.miniquiz.flowers.question': { en: 'What forms after the white coffee flowers fall?', bis: 'Unsa ang maporma human mahulog ang puti nga bulak sa kape?' },
    'ui.miniquiz.flowers.a': { en: 'Small green coffee cherries', bis: 'Gagmayng berde nga bunga sa kape' },
    'ui.miniquiz.flowers.b': { en: 'Small brown coffee cherries', bis: 'Gagmayng brown nga bunga sa kape' },
    'ui.miniquiz.flowers.clue': { en: 'Think about color. Coffee cherries start out unripe — they only turn red much later.', bis: 'Hunahunaa ang kolor. Ang bunga sa kape dili pa hinog sa sinugdan — mamula lamang kini sa ulahi.' },
    'ui.miniquiz.monitoring.question': { en: 'Why are coffee trees regularly monitored?', bis: 'Ngano nga kanunay gibantayan ang mga punoan sa kape?' },
    'ui.miniquiz.monitoring.a': { en: 'To make the coffee trees grow faster', bis: 'Aron mas paspas motubo ang mga punoan sa kape' },
    'ui.miniquiz.monitoring.b': { en: 'To find pests and diseases early', bis: 'Aron sayo nga makita ang mga insekto ug sakit' },
    'ui.miniquiz.monitoring.clue': { en: 'Monitoring doesn\'t change how fast a tree grows. Think about what a farmer is looking for.', bis: 'Ang pagbantay dili makapaspas sa pagtubo sa punoan. Hunahunaa kung unsa ang gipangita sa mag-uuma.' },
};
