// Central UI string table. One entry per user-visible string.
// Read through Scene.prototype.t(key) / window.t(key) — never index this directly.
// 'bis' values are intentionally empty; t() falls back to 'en' until they are filled.
// streetView arrow labels are deliberately NOT here (see commit notes).

window.Strings = {
    'cafe.yfc-board.label': { en: 'YFC Board', bis: '' },
    'cafe.yfc-board.description': { en: 'Aside from the owners\' passion in bringing the farm to the cup, they bring the same passion in dedicating their time in building a Christ-centered community. For over ten years, they faithfully serve as Chapter 5 coordinators of the Youth for Christ Pangantucan Chapter, dedicating their time in being committed to touching countless lives through consistent providing leadership, service, guidance and support to the municipalities of Kalilangan, Pangantucan, and Wao. Their continued dedication reflects a life of selfless service, inspiring communities to grow in faith, unity, and love for God.', bis: '' },
    'cafe.finca-logo.label': { en: 'Finca de Garces Logo', bis: '' },
    'cafe.finca-logo.description': { en: 'This was Finca de Garces\' old logo. Owners decided to renew their branding years later to bring a new face to Finca de Garces while preserving the farm\'s roots.', bis: '' },
    'cafe.bar.label': { en: 'The Bar', bis: '' },
    'cafe.bar.description': { en: 'The bar is where specialty coffee is meticulously crafted, served and discussed. Unlike traditional and commercial cafes, this is where the owners showcase the careful process of pouring a cup of specialty coffee while they engage with visitors.', bis: '' },
    'cafe.coffee-brewing.label': { en: 'Brew Coffee', bis: '' },
    'cafe.coffee-brewing.description': { en: '', bis: '' },
    'cafe.chill-section.label': { en: 'Chill Section', bis: '' },
    'cafe.chill-section.description': { en: 'The owners always emphasize creating connections. The chill section is where customers can play with games, cards and indulge in books to create conversation and a relaxing atmosphere whilst enjoying a cup of coffee.', bis: '' },
    'cafe.exit-to-exterior.description': { en: 'Click to step outside the cafe.', bis: '' },
    'cafe.quiz.question': { en: 'What was the original purpose of opening Alegre Café & Roastery?', bis: '' },
    'cafe.quiz.choice.0': { en: 'To become the largest coffee exporter in the region.', bis: '' },
    'cafe.quiz.choice.1': { en: 'To create a place where people could gather, share stories, and enjoy coffee grown on the family\'s farm.', bis: '' },
    'cafe.quiz.choice.2': { en: 'To sell imported specialty coffee.', bis: '' },
    'cafe.quiz.choice.3': { en: 'To promote tourism in Pangantucan.', bis: '' },
    'cafe.quiz.clue': { en: 'Think about why the family opened the café — it wasn\'t about scale or selling someone else\'s beans.', bis: '' },
    'cafe.quiz.feedback': { en: 'Correct! Alegre Café & Roastery was created as a place where people can connect through coffee while learning the story behind every cup.', bis: '' },
    'cafeExterior.enter-interior.label': { en: 'Enter Cafe', bis: '' },
    'cafeExterior.enter-interior.description': { en: 'Click to go inside.', bis: '' },
    'cafeExterior.to-roastery.label': { en: 'Enter the Roastery', bis: '' },
    'cafeExterior.to-roastery.description': { en: 'Step inside and see where the coffee is roasted.', bis: '' },
    'cafeExterior.to-nursery.label': { en: 'Enter the Nursery', bis: '' },
    'cafeExterior.to-nursery.description': { en: 'Visit the coffee seedling nursery.', bis: '' },
    'cafeExterior.walk-to-farm.label': { en: 'Walk to the Farm', bis: '' },
    'cafeExterior.walk-to-farm.description': { en: 'Take the path from the cafe to the coffee farm.', bis: '' },
    'nursery.back-to-exterior.label': { en: 'Walk to the Farm', bis: '' },
    'nursery.back-to-exterior.description': { en: 'Take the path to the coffee farm.', bis: '' },
    'nursery.seedlings.label': { en: 'Seedlings', bis: '' },
    'nursery.seedlings.description': { en: 'This is where the coffee journey begins. Young plants are nurtured under careful shade and watering conditions before being transplanted to the farm.', bis: '' },
    'nursery.net-shading.label': { en: 'Net Shading', bis: '' },
    'nursery.net-shading.description': { en: 'Black net shading protects the seedlings from direct sun and helps regulate temperature.', bis: '' },
    'nursery.quiz.question': { en: 'How long do young coffee seedlings usually stay in polybags before they are ready for planting?', bis: '' },
    'nursery.quiz.choice.0': { en: '1–2 months', bis: '' },
    'nursery.quiz.choice.1': { en: '3–4 months', bis: '' },
    'nursery.quiz.choice.2': { en: '6–12 months', bis: '' },
    'nursery.quiz.choice.3': { en: '2 years', bis: '' },
    'nursery.quiz.clue': { en: 'Longer than a few months — roots need real time to establish before transplanting.', bis: '' },
    'nursery.quiz.feedback': { en: 'Correct! Seedlings remain in polybags for about six to twelve months, allowing them to develop strong roots before being transplanted.', bis: '' },
    'roastery.back-to-exterior.label': { en: 'Exit to Cafe', bis: '' },
    'roastery.back-to-exterior.description': { en: 'Return to the cafe garden.', bis: '' },
    'roastery.roasting-machine.label': { en: 'Roasting Machine', bis: '' },
    'roastery.roasting-machine.description': { en: 'The roaster applies controlled heat to green coffee beans, moving them through drying, first crack, and development — the stages that build the sugars, acids, and oils responsible for flavour and aroma. Roast time and temperature are adjusted to draw out each bean\'s best character before cooling and packaging.', bis: '' },
    'roastery.roasting-beans-transition.label': { en: 'Roasting Beans', bis: '' },
    'roastery.roasting-beans-transition.description': { en: 'Watch the beans roast', bis: '' },
    'roastery.green-bean-packs.label': { en: 'Green Bean Packs', bis: '' },
    'roastery.green-bean-packs.description': { en: 'Arabica grows at higher elevations and is known for a smoother, more complex, slightly sweet profile with milder acidity. Robusta is hardier, carries more caffeine, and brings a bolder, more bitter character — often used to add body and crema.', bis: '' },
    'roastery.quiz.question': { en: 'What does the \'first crack\' during roasting indicate?', bis: '' },
    'roastery.quiz.choice.0': { en: 'The beans are ready to be planted.', bis: '' },
    'roastery.quiz.choice.1': { en: 'The beans begin developing their full coffee flavor.', bis: '' },
    'roastery.quiz.choice.2': { en: 'The beans have finished cooling.', bis: '' },
    'roastery.quiz.choice.3': { en: 'The beans are ready to be brewed immediately.', bis: '' },
    'roastery.quiz.clue': { en: 'First crack happens in the middle of roasting, not at the end — it\'s about flavor developing.', bis: '' },
    'roastery.quiz.feedback': { en: 'Correct! The first crack signals an important stage where the beans expand and develop the flavors and aromas we associate with coffee.', bis: '' },
    'streetView.quiz.question': { en: 'Why is organic fertilizer added before planting a coffee seedling?', bis: '' },
    'streetView.quiz.choice.0': { en: 'To make the soil richer and help the roots grow well.', bis: '' },
    'streetView.quiz.choice.1': { en: 'To make harvesting easier.', bis: '' },
    'streetView.quiz.choice.2': { en: 'To speed up roasting.', bis: '' },
    'streetView.quiz.choice.3': { en: 'To change the flavor of the coffee immediately.', bis: '' },
    'streetView.quiz.clue': { en: 'Think about what the fertilizer touches first — it goes into the hole, before the tree ever grows.', bis: '' },
    'streetView.quiz.feedback': { en: 'Correct! Healthy coffee trees begin with healthy soil. Preparing the planting hole with organic fertilizer gives young trees the best possible start.', bis: '' },
    'quiz.harvesting.question': { en: 'Which coffee cherries are selected during harvesting?', bis: '' },
    'quiz.harvesting.choice.0': { en: 'Green cherries', bis: '' },
    'quiz.harvesting.choice.1': { en: 'Yellow cherries', bis: '' },
    'quiz.harvesting.choice.2': { en: 'Bright red, fully ripe cherries', bis: '' },
    'quiz.harvesting.choice.3': { en: 'All cherries on the branch', bis: '' },
    'quiz.harvesting.clue': { en: 'Look closely at the colour of the cherries the pickers reach for.', bis: '' },
    'quiz.harvesting.feedback': { en: 'Correct! Only fully ripe cherries are hand-picked to ensure the highest coffee quality.', bis: '' },
    'quiz.backToTheCafe.question': { en: 'What is the main message behind every cup served at Alegre Café & Roastery?', bis: '' },
    'quiz.backToTheCafe.choice.0': { en: 'Coffee is simply a beverage.', bis: '' },
    'quiz.backToTheCafe.choice.1': { en: 'Every cup reflects the care, values, and dedication of the Garces family and their community.', bis: '' },
    'quiz.backToTheCafe.choice.2': { en: 'Coffee is only about roasting.', bis: '' },
    'quiz.backToTheCafe.choice.3': { en: 'Great coffee depends only on expensive equipment.', bis: '' },
    'quiz.backToTheCafe.clue': { en: 'The answer is about people and values, not equipment or a single step in the process.', bis: '' },
    'quiz.backToTheCafe.feedback': { en: 'Correct! Every cup represents the journey from seed to cup, honoring the people, the land, and the passion that made it possible.', bis: '' },
    'quiz.finalChallenge.question': { en: 'Complete the sentence: \'Every cup of coffee begins with...\'', bis: '' },
    'quiz.finalChallenge.choice.0': { en: 'A coffee shop', bis: '' },
    'quiz.finalChallenge.choice.1': { en: 'A roasting machine', bis: '' },
    'quiz.finalChallenge.choice.2': { en: 'A strong foundation, patient care, and dedicated people.', bis: '' },
    'quiz.finalChallenge.choice.3': { en: 'A coffee grinder', bis: '' },
    'quiz.finalChallenge.clue': { en: 'Think back to where the journey actually started — before any machine was involved.', bis: '' },
    'quiz.finalChallenge.feedback': { en: 'Congratulations! You\'ve completed the Coffee Journey. Thank you for exploring the story of Alegre Café & Roastery and discovering how every cup is shaped by the land, the people, and generations of dedication. We hope you\'ll carry this story with you every time you enjoy a cup of coffee. ☕', bis: '' },
    'ui.nursery.toFarm': { en: 'To Farm', bis: '' },
    'ui.video.continue': { en: 'Continue', bis: '' },
    'ui.video.roasteryPrompt': { en: 'Select Continue to visit the roastery', bis: '' },
    'ui.quiz.correct': { en: 'Correct!', bis: '' },
};
